---
version: "3.9"
networks:
  default:
    name: collabstack
services:
  gitlab:
    image: gitlab/gitlab-ce:15.8.0-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2255
        external_url "https://gitlab.nginx.${_SANDBOX_ID}.instruqt.io"
        nginx['listen_port'] = 8000
        nginx['listen_https'] = false
        letsencrypt['enable'] = false
        nginx['proxy_set_headers'] = {
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on"
        }
        mattermost['service_allow_cors_from'] = '*'
        mattermost_nginx['proxy_set_headers'] = {
          "X-Frame-Options" => "SAMEORIGIN",
          "X-Forwarded-Proto" => "https",
          "X-Forwarded-Ssl" => "on",
        }
        mattermost_nginx['listen_port'] = 8065
        mattermost['service_port'] = 8066
        mattermost_nginx['listen_https'] = false
        mattermost_external_url 'https://mattermost.nginx.${_SANDBOX_ID}.instruqt.io'
    ports:
      - "2255:22"
      - "8000:8000"
      - "8065:8065"
    volumes:
      - ./containers/gitlab/config:/etc/gitlab
      - ./containers/gitlab/logs:/var/log/gitlab
      - ./containers/gitlab/data:/var/opt/gitlab
    shm_size: 256m
  wikijs:
    container_name: wikijs
    image: lscr.io/linuxserver/wikijs:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DB_TYPE=sqlite
      - DB_STORAGE=db.sqlite
    volumes:
      - ./containers/wikijs/config:/config
      - ./containers/wikijs/data:/data
    ports: "3000:3000"
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
    volumes:
      - ./containers/nextcloud/config:/config
      - ./containers/nextcloud/data:/data
    ports:
      - "3001:80"
  collabora:
    image: collabora/code:latest
    container_name: collabora
    environment:
      - domain=collabora
      - username=root
      - username=root_password
      - server_name=collabstack
      - extra_params=--o:ssl.enable=false
    ports:
      - "9980:9980"
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: unless-stopped
    environment:
      - TZ=UTC
      - POSTGRES_PASSWORD=postgres_root
      - POSTGRES_DB=mattermost
    volumes:
      - ./containers/postgres/data:/var/lib/postgresql/data
      - ./containers/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
