---
version: "3.9"
networks:
  default:
    name: collabstack
services:
  gitlab:
    image: gitlab/gitlab-ce:15.8.0-ce.0
    container_name: gitlab
    restart: unless-stopped
    hostname: gitlab.nginx.${_SANDBOX_ID}.instruqt.io
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2255
        external_url "https://gitlab.nginx.${_SANDBOX_ID}.instruqt.io"
        letsencrypt['enable'] = false
        mattermost_external_url 'https://mattermost.nginx.${_SANDBOX_ID}.instruqt.io'
        mattermost_nginx['ssl_certificate'] = "/etc/gitlab/ssl/cert.pem"
        mattermost_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/privkey.pem"
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/cert.pem"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/privkey.pem"
        nginx['redirect_http_to_https'] = true
    ports:
      - "2255:22"
      - "8000:80"
      - "4433:443"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    shm_size: 256m
  wikijs:
    container_name: wikijs
    image: lscr.io/linuxserver/wikijs:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DB_TYPE=sqlite
      - DB_STORAGE=db.sqlite
    volumes:
      - ./wikijs/config:/config
      - ./wikijs/data:/data
