---
version: "3.9"
networks:
  default:
    name: collabstack
services:
  gitlab:
    image: gitlab/gitlab-ce:15.8.0-ce.0
    container_name: gitlab
    platform: linux/amd64
    restart: unless-stopped
    hostname: gitlab.${COLLABSTACK_HOSTNAME}
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['gitlab_shell_ssh_port'] = 2255
        mattermost_external_url 'http://mattermost.${COLLABSTACK_HOSTNAME}'
    ports:
      - 2255:22
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
      - ./gitlab/nginx:/nginx
    shm_size: 256m
  wikijs:
    container_name: wikijs
    image: lscr.io/linuxserver/wikijs:latest
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DB_TYPE=sqlite
      - DB_STORAGE=db.sqlite
    volumes:
      - ./wikijs/config:/config
      - ./wikijs/data:/data
  nginx:
    depends_on:
      - gitlab
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    pids_limit: 100
    read_only: true
    tmpfs:
      - /var/run
      - /var/cache
      - /var/log/nginx
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/dhparams4096.pem}:/dhparams4096.pem
    environment:
      - TZ=UTC
    ports:
      - 443:443
      - 80:80
